vich_uploader:
    db_driver: orm

    mappings:
        entreprises_images:
            uri_prefix:          '%app.path.images_entreprises%'
            upload_destination: '%kernel.project_dir%/public%app.path.images_entreprises%' 
            namer: vich_uploader.namer_uniqid
